version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/read_share
      - JWT_SECRET=fghytu_oihf
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./backup:/backup
    entrypoint: [ "/bin/bash", "-c", "/backup/init-mongo.sh && docker-entrypoint.sh mongod" ]

volumes:
  mongo-data:
